x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: 100

networks:
  docker-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=${POSTGRESQL_PORT}
      - DATABASE_USERNAME=${POSTGRESQL_USERNAME}
      - DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - DATABASE_NAME=${POSTGRESQL_DATABASE}
    depends_on:
      - postgres_db
    networks:
      - docker-network
    logging: *default-logging

  postgres_db:
    image: bitnami/postgresql:latest
    platform: linux/amd64 
    container_name: postgres_db
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - docker-network
    logging: *default-logging

volumes:
  db-data:
