x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: 100



services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ../backend/.env.prod
    environment:
      - SEQ_URL=http://seq:5341 
    depends_on:
      - postgres_db
      - seq
    networks:
      - docker-network
    logging: *default-logging

  postgres_db:
    image: bitnami/postgresql:latest
    platform: linux/amd64 
    container_name: postgres_db
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - docker-network
    logging: *default-logging

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:5341"  # API port
      - "8081:80"    # Web UI port
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    networks:
      - docker-network
    logging: *default-logging
    
volumes:
  db-data:
  seq-data:  

networks:
  docker-network:
    driver: bridge